indent error need to resolve: flask.cli.NoAppException: While importing "application", an ImportError was raised:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
  File "/Users/grace/Downloads/finance/application.py", line 5, in <module>
    from flask_session import Session
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask_session/__init__.py", line 16, in <module>
    from .sessions import NullSessionInterface, RedisSessionInterface, \
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask_session/sessions.py", line 23, in <module>
    from itsdangerous import Signer, BadSignature, want_bytes
ImportError: cannot import name 'want_bytes'